export const departments = [
  {
    code: "DK",
    title: "Deck",
    name: { ka: "საბჭოს გუნდი", en: "Deck Crew" },
    roles: {
      ka: "კაპიტანი · მეზღვაური · ბოცმანი",
      en: "Captain · Sailor · Boatswain",
    },
    open: 24,
  },
  {
    code: "EN",
    title: "Engine",
    name: { ka: "მანქანის განყოფილება", en: "Engine Department" },
    roles: {
      ka: "მთავარი მექანიკოსი · მემანქანე · ელექტრიკოსი",
      en: "Chief Engineer · Motorman · Electrician",
    },
    open: 31,
  },
  {
    code: "GL",
    title: "Galley",
    name: { ka: "სამზარეულო", en: "Galley & Catering" },
    roles: {
      ka: "შეფ-მზარეული · სტიუარდი",
      en: "Chef · Steward",
    },
    open: 12,
  },
  {
    code: "BR",
    title: "Bridge",
    name: { ka: "სამეთაურო ხიდი", en: "Bridge Command" },
    roles: {
      ka: "სტარშ. თანაშემწე · ნავიგატორი · რადისტი",
      en: "Chief Officer · Navigator · Radio Operator",
    },
    open: 20,
  },
];

export const jobs = [
  {
    id: "dk-101",
    dept: "DK",
    rank: { ka: "კაპიტანი", en: "Captain" },
    vessel: { ka: "საკონტეინერო გემი · 8,200 TEU", en: "Container Ship · 8,200 TEU" },
    zone: { ka: "შავი ზღვა — ხმელთაშუა ზღვა", en: "Black Sea — Mediterranean" },
    agency: { ka: "ბათუმის საკადრო სააგენტო", en: "Batumi Crewing Agency" },
    contract: { ka: "6 თვე", en: "6 months" },
    salary: "$9,500/თვე",
    postedDaysAgo: 1,
    urgent: true,
  },
  {
    id: "dk-102",
    dept: "DK",
    rank: { ka: "მეზღვაური", en: "Sailor (AB)" },
    vessel: { ka: "სამეთაურო ტანკერი", en: "Product Tanker" },
    zone: { ka: "ხმელთაშუა ზღვა", en: "Mediterranean" },
    agency: { ka: "შავიზღვის ეკიპაჟი", en: "Black Sea Crew Ltd." },
    contract: { ka: "4 თვე", en: "4 months" },
    salary: "$2,100/თვე",
    postedDaysAgo: 3,
    urgent: false,
  },
  {
    id: "dk-103",
    dept: "DK",
    rank: { ka: "ბოცმანი", en: "Boatswain" },
    vessel: { ka: "მშრალტვირთა გემი", en: "Bulk Carrier" },
    zone: { ka: "წითელი ზღვა — სპარსეთის ყურე", en: "Red Sea — Persian Gulf" },
    agency: { ka: "ნავიგო კრიუინგი", en: "Navigo Crewing" },
    contract: { ka: "5 თვე", en: "5 months" },
    salary: "$2,800/თვე",
    postedDaysAgo: 6,
    urgent: false,
  },
  {
    id: "en-201",
    dept: "EN",
    rank: { ka: "მთავარი მექანიკოსი", en: "Chief Engineer" },
    vessel: { ka: "საკონტეინერო გემი · 8,200 TEU", en: "Container Ship · 8,200 TEU" },
    zone: { ka: "შავი ზღვა — ხმელთაშუა ზღვა", en: "Black Sea — Mediterranean" },
    agency: { ka: "ბათუმის საკადრო სააგენტო", en: "Batumi Crewing Agency" },
    contract: { ka: "6 თვე", en: "6 months" },
    salary: "$8,200/თვე",
    postedDaysAgo: 2,
    urgent: true,
  },
  {
    id: "en-202",
    dept: "EN",
    rank: { ka: "მემანქანე", en: "Motorman" },
    vessel: { ka: "ქიმტანკერი", en: "Chemical Tanker" },
    zone: { ka: "ჩრდილოეთის ზღვა", en: "North Sea" },
    agency: { ka: "პორტალიანსი", en: "Port Alliance" },
    contract: { ka: "4 თვე", en: "4 months" },
    salary: "$2,600/თვე",
    postedDaysAgo: 4,
    urgent: false,
  },
  {
    id: "en-203",
    dept: "EN",
    rank: { ka: "ელექტრიკოსი", en: "Electrician" },
    vessel: { ka: "მგზავრთმზიდი ლაინერი", en: "Passenger Liner" },
    zone: { ka: "კარიბის ზღვა", en: "Caribbean" },
    agency: { ka: "შავიზღვის ეკიპაჟი", en: "Black Sea Crew Ltd." },
    contract: { ka: "8 თვე", en: "8 months" },
    salary: "$3,400/თვე",
    postedDaysAgo: 9,
    urgent: false,
  },
  {
    id: "gl-301",
    dept: "GL",
    rank: { ka: "შეფ-მზარეული", en: "Chef" },
    vessel: { ka: "მგზავრთმზიდი ლაინერი", en: "Passenger Liner" },
    zone: { ka: "კარიბის ზღვა", en: "Caribbean" },
    agency: { ka: "პორტალიანსი", en: "Port Alliance" },
    contract: { ka: "8 თვე", en: "8 months" },
    salary: "$3,100/თვე",
    postedDaysAgo: 5,
    urgent: false,
  },
  {
    id: "gl-302",
    dept: "GL",
    rank: { ka: "სტიუარდი", en: "Steward" },
    vessel: { ka: "მგზავრთმზიდი ლაინერი", en: "Passenger Liner" },
    zone: { ka: "ხმელთაშუა ზღვა", en: "Mediterranean" },
    agency: { ka: "ნავიგო კრიუინგი", en: "Navigo Crewing" },
    contract: { ka: "6 თვე", en: "6 months" },
    salary: "$1,900/თვე",
    postedDaysAgo: 7,
    urgent: false,
  },
  {
    id: "br-401",
    dept: "BR",
    rank: { ka: "სტარშ. თანაშემწე", en: "Chief Officer" },
    vessel: { ka: "საკონტეინერო გემი · 8,200 TEU", en: "Container Ship · 8,200 TEU" },
    zone: { ka: "შავი ზღვა — ხმელთაშუა ზღვა", en: "Black Sea — Mediterranean" },
    agency: { ka: "ბათუმის საკადრო სააგენტო", en: "Batumi Crewing Agency" },
    contract: { ka: "6 თვე", en: "6 months" },
    salary: "$6,400/თვე",
    postedDaysAgo: 1,
    urgent: true,
  },
  {
    id: "br-402",
    dept: "BR",
    rank: { ka: "ნავიგატორი", en: "Navigator" },
    vessel: { ka: "მშრალტვირთა გემი", en: "Bulk Carrier" },
    zone: { ka: "წითელი ზღვა — სპარსეთის ყურე", en: "Red Sea — Persian Gulf" },
    agency: { ka: "ნავიგო კრიუინგი", en: "Navigo Crewing" },
    contract: { ka: "5 თვე", en: "5 months" },
    salary: "$4,300/თვე",
    postedDaysAgo: 4,
    urgent: false,
  },
  {
    id: "br-403",
    dept: "BR",
    rank: { ka: "რადისტი", en: "Radio Operator" },
    vessel: { ka: "სამეთაურო ტანკერი", en: "Product Tanker" },
    zone: { ka: "ჩრდილოეთის ზღვა", en: "North Sea" },
    agency: { ka: "პორტალიანსი", en: "Port Alliance" },
    contract: { ka: "4 თვე", en: "4 months" },
    salary: "$3,700/თვე",
    postedDaysAgo: 10,
    urgent: false,
  },
];

export const stages = [
  {
    leg: "01",
    title: { ka: "გამგზავრება", en: "Departure" },
    desc: {
      ka: "ატვირთე სერტიფიკატები — STCW, GMDSS, სამედიცინო ცნობა — და შეავსე გამოცდილების ჟურნალი.",
      en: "Upload your certificates — STCW, GMDSS, medical certificate — and fill out your experience log.",
    },
  },
  {
    leg: "02",
    title: { ka: "ვერიფიკაცია", en: "Verification" },
    desc: {
      ka: "ჩვენი გუნდი ამოწმებს დოკუმენტებს 24 საათში. მხოლოდ დადასტურებული პროფილები ჩანს დამსაქმებლისთვის.",
      en: "Our team verifies documents within 24 hours. Only confirmed profiles are visible to employers.",
    },
  },
  {
    leg: "03",
    title: { ka: "მიმაგრება", en: "Placement" },
    desc: {
      ka: "მიიღე შეთავაზება ვერიფიცირებული სააგენტოსგან, გაფორმდი კონტრაქტი და აგზავნი ბარგს ნავსადგურისკენ.",
      en: "Receive an offer from a verified agency, sign the contract, and send your bags to the port.",
    },
  },
];
